### ISSUE TITLE
OSError: File task2/save_tensorflow/temp.meta does not exist.

### ISSUE THREAD

**Issue by Fansgithub2019** [VinodS7/audio-adversaries#1]
(tensorflow) (base) PS D:\Documents\paper\audio-adversaries-master\audio-adversaries-master\src> python main.py
Started timer
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    deepfool_main.deepfoolcochlear(FLAGS.audio_path,FLAGS.metadata_path,FLAGS.model_path,FLAGS.exp_data_path,FLAGS.adv_audio_path,FLAGS.save_data)
  File "D:\Documents\paper\audio-adversaries-master\audio-adversaries-master\src\deepfool_main.py", line 116, in deepfoolcochlear
    saver= model.build_graph(pcm)
  File "D:\Documents\paper\audio-adversaries-master\audio-adversaries-master\src\cleverhans_wrapper.py", line 57, in build_graph
    self.saver = tf.train.import_meta_graph(self.checkpoint,input_map={'input_1:0':pcm})
  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1447, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "D:\Program Files\Anconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 633, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
OSError: File task2/save_tensorflow/temp.meta does not exist.

Is there any file task2 in your code?

**Comment by VinodS7** [comment]
So the folder task2 is leading to this .meta file where the tensorflow model is saved. It is too large to upload it onto github.
